services:
  web:
    build: .
    networks: [ webnet ]

  caddy:
    image: caddy:alpine
    ports: ["80:80", "443:443"]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [ webnet ]
    depends_on: [ web ]

networks: { webnet: {} }
volumes: { caddy_data: {}, caddy_config: {} }
